# Generated by Django 5.0.6 on 2024-06-26 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('nama', models.CharField(max_length=255)),
                ('namawali', models.CharField(max_length=255)),
                ('nohpwali', models.CharField(max_length=255)),
                ('nomorinduk', models.IntegerField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('jumlah', models.IntegerField(max_length=255)),
                ('detail', models.CharField(max_length=300)),
                ('tglbayar', models.DateTimeField()),
                ('bendahara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.siswa')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
