# Generated by Django 5.0.6 on 2024-06-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembayaran',
            name='tglbayar',
            field=models.DateField(),
        ),
    ]
