# Generated by Django 5.0.6 on 2024-06-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_alter_pembayaran_tglbayar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembayaran',
            name='jumlah',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='nomorinduk',
            field=models.IntegerField(unique=True),
        ),
    ]
